### PR TITLE
Fix KEY_BACKSLASH mapping

### PR DESCRIPTION
**Pull request by SpiritCroc**
Tested with US-layout. I don't know where the original value comes from, I guess it wasn't tested due to layout differences to German layout, or does this differ on some devices?

An update in the neighbor table would probably also make sense (same for the FN key pull request).

### CODE REVIEW

**Comment by duncanthrax** [comment]
I remember backslash key being an oddball when I built the tables. When you say "US layout", you mean the US hardware (with the small enter key), right? Which of the two product IDs (307a or 3098) do you have?

**Comment by SpiritCroc** [comment]
Yes, keyboard with US ANSI layout like here https://images-na.ssl-images-amazon.com/images/I/71AD%2BTAMJVL._SL1500_.jpg

Product ID is 307a.

**Comment by duncanthrax** [comment]
Hmpf. I use EU HW with US layout. For historical reasons. I can't stand the small enter key :/

Anyway, it means we need to find a way to differentiate the HW types, because the product ID is only different between the 100/120 models, not the keyboard HW layout.

**Comment by SpiritCroc** [comment]
I see. In case you come up with something and/or need some US-HW user feedback, feel free to tell me :)

Having used German keyboards in the past myself, the different keys did take some time getting used to, but now, I'm actually better with US ANSI layout than German ISO

**Comment by SpiritCroc** [comment]
https://github.com/duncanthrax/roccat-vulcan/pull/7

**Pull request closed without merging**
